# Generated by Django 2.2 on 2019-12-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_size', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('traffic_day', models.CharField(max_length=255)),
                ('traffic_night', models.CharField(max_length=255)),
                ('distance_from_the_street', models.CharField(max_length=255)),
                ('cctv', models.BooleanField()),
                ('locals_night', models.BooleanField()),
                ('fence', models.CharField(max_length=255)),
                ('landform', models.CharField(max_length=255)),
                ('neighboring_buildings', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(max_length=255)),
                ('service_building', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PrivateObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_private_building_value', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='PublicObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitors_per_hour', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=255)),
                ('total_products_value', models.DecimalField(decimal_places=2, max_digits=2)),
                ('products_amount', models.IntegerField()),
                ('large_safe', models.BooleanField()),
                ('small_safe', models.BooleanField()),
                ('total_service_building_value', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
    ]
