# Generated by Django 2.2 on 2020-01-31 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime_name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, max_length=255, null=True, upload_to='media/')),
                ('chart', models.ImageField(blank=True, max_length=255, null=True, upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='DistrictVisually',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('crimes', models.ManyToManyField(to='Survey.Crimes')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_type', models.CharField(choices=[('0', 'Mała ulica, wioska'), ('1', 'Ulica średniej wielkości lub mało ruchliwe przedmieścia miasta'), ('2', 'Ulica lub ciąg komunikacyjny o dużym natężeniu ruchu')], max_length=255)),
                ('cctv', models.BooleanField(default=False)),
                ('locals_night', models.BooleanField(default=False)),
                ('neighboring_buildings', models.CharField(choices=[('1', 'Brak lub daleko (ponad 100 m)'), ('2', 'Domy jednorodzinne'), ('3', 'Bloki mieszkalne'), ('4', 'Budynki usługowe'), ('5', 'Obiekty sportowe lub rozrywkowe')], max_length=255)),
                ('flammable_materials', models.BooleanField(default=False)),
                ('district', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Survey.DistrictVisually')),
            ],
        ),
        migrations.CreateModel(
            name='SecurityDegree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_trading_building_value', models.CharField(choices=[('0', 'Wartość do 500 tys.'), ('1', 'Wartość  powyżej > 500 tys.'), ('2', 'Wartość powyżej > 1 000 tys.'), ('3', 'Wartość powyżej > 1 500 tys.')], max_length=200)),
                ('total_service_building_value', models.CharField(choices=[('0', 'Wartość do 500 tys.'), ('1', 'Wartość  powyżej > 500 tys.'), ('2', 'Wartość powyżej > 1 000 tys.'), ('3', 'Wartość powyżej > 1 500 tys.')], max_length=200)),
                ('total_private_building_value', models.CharField(choices=[('0', 'Wartość do 500 tys.'), ('1', 'Wartość  powyżej > 500 tys.'), ('2', 'Wartość powyżej > 1 000 tys.'), ('3', 'Wartość powyżej > 1 500 tys.')], max_length=200)),
                ('visitors_per_hour', models.CharField(choices=[('0', 'kilka do kilkunastu osób'), ('1', 'do 100 osób'), ('2', 'od 100 do 300'), ('3', 'powyżej 300')], max_length=200)),
                ('object_priority', models.CharField(choices=[('0', 'Obiekt NIEZALICZANY do infrastruktury krytycznej'), ('1', 'Obiekt ZALICZANY do infrastruktury krytycznej')], max_length=255)),
                ('object_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Survey.ObjectData')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('0', 'Obiekt handlowy'), ('1', 'Obiekt usługowy - prywatny'), ('2', 'Obiekt prywatny'), ('3', 'Obiekt publiczny')], default='0', max_length=255)),
                ('service_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Survey.ServiceObject')),
            ],
        ),
    ]
