# Generated by Django 2.2 on 2020-01-14 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_size', models.CharField(choices=[('1', 'Parterowy'), ('2', 'Niski'), ('3', 'Średnio wysoki'), ('4', 'Wysokościowy')], max_length=255)),
                ('district', models.CharField(choices=[('1', 'Bemowo'), ('2', 'Białołęka'), ('3', 'Bielany'), ('4', 'Mokotów'), ('5', 'Ochota'), ('6', 'Praga Pd.'), ('7', 'Praga Pn.'), ('8', 'Rembertów'), ('9', 'Targówek'), ('10', 'Ursus'), ('11', 'Ursynów'), ('12', 'Wawer'), ('13', 'Wesoła'), ('14', 'Wilanów'), ('15', 'Włochy'), ('16', 'Wola'), ('17', 'Żoliborz')], max_length=255)),
                ('traffic_day', models.CharField(choices=[('1', '0-5 aut/min'), ('2', '5-10 aut/min'), ('3', '10-50 aut/min'), ('4', '50-100 aut/min'), ('5', '100 < aut/min')], max_length=255)),
                ('traffic_night', models.CharField(choices=[('1', '0-1 aut/min'), ('2', '1-5 aut/min'), ('3', '5-10 aut/min'), ('4', '10-50 aut/min'), ('5', '50 < aut/min')], max_length=255)),
                ('distance_from_the_street', models.CharField(choices=[('1', '<5 m'), ('2', '5-10 m'), ('3', '10 < m')], max_length=255)),
                ('cctv', models.BooleanField(default=False)),
                ('locals_night', models.BooleanField(default=False)),
                ('fence', models.CharField(choices=[('1', 'Brak'), ('2', 'Niski płotek'), ('3', 'Płot o wysokości około 1,5 m'), ('4', 'Wysoki płot'), ('5', 'Płot 2-metrowy wraz z drutem kolczastym 0,5-metrowym')], max_length=255)),
                ('landform', models.CharField(choices=[('1', 'W zagłębieniu terenu do około 5m'), ('2', 'Równy teren'), ('3', 'Obok rzeki'), ('4', 'Na wzniesieniu terenu')], max_length=255)),
                ('neighboring_buildings', models.CharField(choices=[('1', 'Brak lub daleko (ponad 100 m)'), ('2', 'Domy jednorodzinne'), ('3', 'Bloki mieszkalne'), ('4', 'Budynki usługowe'), ('5', 'Obiekty sportowe lub rozrywkowe')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_products_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('products_amount', models.IntegerField(blank=True, null=True)),
                ('safe_size', models.CharField(blank=True, choices=[('0', 'Mały sejf'), ('1', 'Duży sejf')], max_length=255, null=True)),
                ('total_service_building_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_private_building_value', models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True)),
                ('visitors_per_hour', models.IntegerField(blank=True, null=True)),
                ('object_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Survey.ObjectData')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(blank=True, choices=[('0', 'Obiekt usług handlowych'), ('1', 'Obiekt usług bankowych'), ('2', 'Obiekt usług innych'), ('3', 'Obiekt prywatny'), ('4', 'Obiekt publiczny')], default='0', max_length=255, null=True)),
                ('service_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Survey.ServiceObject')),
            ],
        ),
    ]
