# Generated by Django 2.2 on 2019-12-17 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objecttype',
            name='service_building',
        ),
        migrations.RemoveField(
            model_name='serviceobject',
            name='large_safe',
        ),
        migrations.RemoveField(
            model_name='serviceobject',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='serviceobject',
            name='small_safe',
        ),
        migrations.AddField(
            model_name='serviceobject',
            name='safe_size',
            field=models.CharField(choices=[('0', 'Mały sejf'), ('1', 'Duży sejf')], default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='objectdata',
            name='distance_from_the_street',
            field=models.CharField(choices=[('1', '<5 m')], max_length=255),
        ),
        migrations.AlterField(
            model_name='objectdata',
            name='district',
            field=models.CharField(choices=[('Bemowo', 'Bemowo')], max_length=255),
        ),
        migrations.AlterField(
            model_name='objectdata',
            name='object_size',
            field=models.CharField(choices=[('parterowy', 'parterowy')], max_length=255),
        ),
        migrations.AlterField(
            model_name='objectdata',
            name='traffic_day',
            field=models.CharField(choices=[('1', '0-5 aut/min')], max_length=255),
        ),
        migrations.AlterField(
            model_name='objectdata',
            name='traffic_night',
            field=models.CharField(choices=[('1', '0-1 aut/min')], max_length=255),
        ),
        migrations.AlterField(
            model_name='objecttype',
            name='object_type',
            field=models.CharField(blank=True, choices=[('Obiekt usługowy', 'Obiekt usługowy'), ('Obiekt prywatny', 'Obiekt prywatny'), ('Obiekt publiczny', 'Obiekt publiczny')], max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('Trade', 'Usługi Handlowe'), ('Banking', 'Usługi Bankowe'), ('Other', 'Inne Usługi')], max_length=255)),
                ('service_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Survey.ServiceObject')),
            ],
        ),
    ]
