# Generated by Django 2.2 on 2020-01-31 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crimes',
            name='chart',
        ),
    ]
