# Generated by Django 2.2 on 2020-01-31 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0002_remove_crimes_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimes',
            name='chart',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='media/'),
        ),
    ]
