# Generated by Django 2.2 on 2019-12-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0003_auto_20191217_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectdata',
            name='cctv',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='objectdata',
            name='locals_night',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='serviceobject',
            name='total_products_value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='serviceobject',
            name='total_service_building_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
