# Generated by Django 2.2 on 2019-12-17 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0004_auto_20191217_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objecttype',
            name='object_data',
        ),
        migrations.RemoveField(
            model_name='privateobject',
            name='object_type',
        ),
        migrations.RemoveField(
            model_name='publicobject',
            name='object_type',
        ),
        migrations.RemoveField(
            model_name='servicetype',
            name='object_type',
        ),
        migrations.AddField(
            model_name='objectdata',
            name='object_type',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='Survey.ObjectType'),
            preserve_default=False,
        ),
    ]
