# Generated by Django 2.2 on 2019-12-17 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0005_auto_20191217_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectdata',
            name='object_type',
        ),
        migrations.AddField(
            model_name='objecttype',
            name='object_data',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='Survey.ObjectData'),
            preserve_default=False,
        ),
    ]
