# Generated by Django 2.2 on 2019-12-17 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0006_auto_20191217_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objecttype',
            name='object_data',
        ),
    ]
